export const COLORS = {
  PRIMARY_DARK: '#0E151A',
  SECONDARY_DARK: '#134156', 
  ACCENT_GREEN: '#00B49F',
  BRIGHT_GREEN: '#14F1B2',
  LIGHT_GREEN: '#8DFFF0',
  LIGHTEST_GREEN: '#C5FFF8',
  WHITE: '#FFFFFF',
  BLACK: '#000000',
  GRAY: '#6B7280',
  LIGHT_GRAY: '#9CA3AF'
}

export const GRADIENTS = {
  PRIMARY: [COLORS.PRIMARY_DARK, COLORS.SECONDARY_DARK],
  GREEN: [COLORS.ACCENT_GREEN, COLORS.BRIGHT_GREEN],
  LIGHT_GREEN: [COLORS.LIGHT_GREEN, COLORS.LIGHTEST_GREEN]
}

export const FONTS = {
  REGULAR: 'SpaceMono',
  BOLD: 'SpaceMono-Bold'
}

export const SPACING = {
  XS: 4,
  SM: 8,
  MD: 16,
  LG: 24,
  XL: 32,
  XXL: 48
}
